apiVersion: v1
kind: Service
metadata: 
  name: rabbitmqnpservice-srv
spec: 
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 80
      targetPort: 80    